Repository SamarthTech/web-projects-2024, pull requests merged in 2024-09, with the labels that each got.

#9 feat: added Reddit-Memes
  Reddit-Memes/.eslintrc.cjs
  Reddit-Memes/.gitignore
  Reddit-Memes/README.md
  Reddit-Memes/bun.lockb
  Reddit-Memes/index.html
  Reddit-Memes/package-lock.json
  Reddit-Memes/package.json
  Reddit-Memes/postcss.config.js
  Reddit-Memes/src/App.jsx
  Reddit-Memes/src/Components/Button.jsx
  Reddit-Memes/src/Components/Meme.jsx
  Reddit-Memes/src/index.css
  Reddit-Memes/src/main.jsx
  Reddit-Memes/tailwind.config.js
  Reddit-Memes/vite.config.js
Labels: hacktoberfest-accepted

#5 <Add QR code generator>
  Qr code generator/QR CODE GENERATOR codes.txt
  Qr code generator/QR CODE GENERATOR.html
Labels: hacktoberfest-accepted

#2 Added Retro Car Racing Game
  Retro Racing Game/1.js
  Retro Racing Game/1icon.png
  Retro Racing Game/car04.png
  Retro Racing Game/cloud.jpg
  Retro Racing Game/finish.png
  Retro Racing Game/hero.png
  Retro Racing Game/icon.png
  Retro Racing Game/index.html
  Retro Racing Game/null.js
  Retro Racing Game/style.css
  Retro Racing Game/tree.png
Labels: good first issue, hacktoberfest-accepted

#13 Added password generator
  React-Password-Generator/.gitignore
  React-Password-Generator/README.md
  React-Password-Generator/package-lock.json
  React-Password-Generator/package.json
  React-Password-Generator/public/favicon.ico
  React-Password-Generator/public/index.html
  React-Password-Generator/public/logo192.png
  React-Password-Generator/public/logo512.png
  React-Password-Generator/public/manifest.json
  React-Password-Generator/public/robots.txt
  React-Password-Generator/src/App.css
  React-Password-Generator/src/App.js
  React-Password-Generator/src/App.test.js
  React-Password-Generator/src/Character.js
  React-Password-Generator/src/index.css
  React-Password-Generator/src/index.js
  React-Password-Generator/src/logo.svg
  React-Password-Generator/src/message.js
  React-Password-Generator/src/reportWebVitals.js
  React-Password-Generator/src/setupTests.js
Labels: hacktoberfest-accepted, hacktoberfest
