Repository SamarthTech/web-projects-2024, pull requests merged in 2024-10, with the labels that each got.

#14 dapp-todo-list
  dapp-todo-list/.gitattributes
  dapp-todo-list/.gitignore
  dapp-todo-list/LICENSE
  dapp-todo-list/README.md
  dapp-todo-list/contracts/.gitkeep
  dapp-todo-list/contracts/TodoList.sol
  dapp-todo-list/migrations/.gitkeep
  dapp-todo-list/migrations/2_deploy_contracts.js
  dapp-todo-list/package-lock.json
  dapp-todo-list/package.json
  dapp-todo-list/postcss.config.js
  dapp-todo-list/public/favicon.ico
  dapp-todo-list/public/index.html
  dapp-todo-list/public/manifest.json
  dapp-todo-list/public/robots.txt
  dapp-todo-list/public/todo.png
  dapp-todo-list/src/App.css
  dapp-todo-list/src/App.js
  dapp-todo-list/src/App.test.js
  dapp-todo-list/src/EthereumContext.js
  dapp-todo-list/src/TodoList.js
  dapp-todo-list/src/index.css
  dapp-todo-list/src/index.js
  dapp-todo-list/src/logo.svg
  dapp-todo-list/src/reportWebVitals.js
  dapp-todo-list/src/setupTests.js
  dapp-todo-list/tailwind.config.js
  dapp-todo-list/test/.gitkeep
  dapp-todo-list/truffle-config.js
  ping-pong-game/LICENSE
  ping-pong-game/README.md
  ping-pong-game/Sounds/comScore.mp3
  ping-pong-game/Sounds/hit.mp3
  ping-pong-game/Sounds/userScore.mp3
  ping-pong-game/Sounds/wall.mp3
  ping-pong-game/index.html
  ping-pong-game/pong.js
Labels: hacktoberfest-accepted, hacktoberfest

#18 Added Download Button for Generated QR Code
  Breakout-game/breakout.css
  Breakout-game/breakout.js
  Breakout-game/breakout_bg.png
  Breakout-game/index.html
  Qr code generator/QR CODE GENERATOR codes.txt
  Qr code generator/QR CODE GENERATOR.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#15 added whiteboard web app
  whiteboardapp/.eslintrc.json
  whiteboardapp/.gitignore
  whiteboardapp/README.md
  whiteboardapp/app/component.js
  whiteboardapp/app/favicon.ico
  whiteboardapp/app/fonts/GeistMonoVF.woff
  whiteboardapp/app/fonts/GeistVF.woff
  whiteboardapp/app/globals.css
  whiteboardapp/app/layout.js
  whiteboardapp/app/page.js
  whiteboardapp/jsconfig.json
  whiteboardapp/next.config.mjs
  whiteboardapp/package-lock.json
  whiteboardapp/package.json
  whiteboardapp/postcss.config.mjs
  whiteboardapp/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest

#22 add cyberpunk ai image generator
  ai-image-generator/cyberpunk.webp
  ai-image-generator/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#16 Added Real Time Chat Application
  React-Password-Generator/README.md
  React-Real-Time-Chat/.firebaserc
  React-Real-Time-Chat/.gitattributes
  React-Real-Time-Chat/.gitignore
  React-Real-Time-Chat/LICENSE
  React-Real-Time-Chat/README.md
  React-Real-Time-Chat/firebase.json
  React-Real-Time-Chat/package-lock.json
  React-Real-Time-Chat/package.json
  React-Real-Time-Chat/postcss.config.js
  React-Real-Time-Chat/public/favicon.ico
  React-Real-Time-Chat/public/index.html
  React-Real-Time-Chat/public/logo192.png
  React-Real-Time-Chat/public/logo512.png
  React-Real-Time-Chat/public/manifest.json
  React-Real-Time-Chat/public/robots.txt
  React-Real-Time-Chat/src/App.css
  React-Real-Time-Chat/src/App.js
  React-Real-Time-Chat/src/App.test.js
  React-Real-Time-Chat/src/components/Chat.js
  React-Real-Time-Chat/src/components/Login.js
  React-Real-Time-Chat/src/firebase.js
  React-Real-Time-Chat/src/index.css
  React-Real-Time-Chat/src/index.js
  React-Real-Time-Chat/src/logo.svg
  React-Real-Time-Chat/src/reportWebVitals.js
  React-Real-Time-Chat/src/setupTests.js
  React-Real-Time-Chat/src/styles/ChatStyles.js
  React-Real-Time-Chat/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest

#63 Added Snake Game #51
  snake game/index.html
  snake game/script.js
  snake game/style.css
Labels: dino-accepted, open-odyssey

#61 Expense Tracker API added
  expense-tracker-api/.env.sample.txt
  expense-tracker-api/.gitignore
  expense-tracker-api/Dockerfile
  expense-tracker-api/README.md
  expense-tracker-api/docker-compose.yml
  expense-tracker-api/package-lock.json
  expense-tracker-api/package.json
  expense-tracker-api/prisma/migrations/20240926101131_init/migration.sql
  expense-tracker-api/prisma/migrations/20240926113802_new_migrate/migration.sql
  expense-tracker-api/prisma/migrations/20240927122032_titleadd/migration.sql
  expense-tracker-api/prisma/migrations/migration_lock.toml
  expense-tracker-api/prisma/schema.prisma
  expense-tracker-api/src/imports.ts
  expense-tracker-api/src/index.ts
  expense-tracker-api/src/middleware/auth.ts
  expense-tracker-api/src/routes/expense.ts
  expense-tracker-api/src/routes/routes.ts
  expense-tracker-api/src/utils/category.ts
  expense-tracker-api/tsconfig.json
Labels: dino-accepted, open-odyssey

#30 Added a Game for cricket lovers.
  Luck-Cricket-Game/README.md
  Luck-Cricket-Game/ball.png
  Luck-Cricket-Game/bat.png
  Luck-Cricket-Game/choose.png
  Luck-Cricket-Game/index.html
  Luck-Cricket-Game/script.js
  Luck-Cricket-Game/style.css
Labels: dino-accepted

#37 added balloon popper
  balloon popper/index.html
  balloon popper/script.js
  balloon popper/style.css
Labels: dino-accepted, open-odyssey

#40 Added sudoko game
  Sudoku/index.html
  Sudoku/manifest.json
  Sudoku/scripts/script.js
  Sudoku/src/styles.css
Labels: good first issue, dino-accepted

#45 Project : Bible verse Generator
  Bible-Verse-Generator/.gitignore
  Bible-Verse-Generator/README.md
  Bible-Verse-Generator/eslint.config.js
  Bible-Verse-Generator/index.html
  Bible-Verse-Generator/package-lock.json
  Bible-Verse-Generator/package.json
  Bible-Verse-Generator/public/vite.svg
  Bible-Verse-Generator/src/App.css
  Bible-Verse-Generator/src/App.jsx
  Bible-Verse-Generator/src/components/RandomVerse.css
  Bible-Verse-Generator/src/components/RandomVerse.jsx
  Bible-Verse-Generator/src/components/RetrievalButton.css
  Bible-Verse-Generator/src/components/RetrievalButton.jsx
  Bible-Verse-Generator/src/index.css
  Bible-Verse-Generator/src/main.jsx
  Bible-Verse-Generator/vite.config.js
Labels: dino-accepted, open-odyssey

#48 made changes to Portfolio website
  PORTFOLIO/PORTFOLIO.html
  PORTFOLIO/style.css
Labels: dino-accepted

#49 Added my web portfolio
  Web-Portfolio/README.md
  Web-Portfolio/assets/ascii_renderer/img1.jpeg
  Web-Portfolio/assets/ascii_renderer/img2.jpeg
  Web-Portfolio/assets/blender/headphone.png
  Web-Portfolio/assets/blender/nightCity.png
  Web-Portfolio/assets/c4online/img1.png
  Web-Portfolio/assets/c4online/img2.png
  Web-Portfolio/index.html
  Web-Portfolio/scripts/profileDescInterp.js
  Web-Portfolio/styles/base.css
Labels: dino-accepted

#50 Hackathon Tracker
  Hackathon Tracker/index.html
  Hackathon Tracker/script.js
  Hackathon Tracker/style.css
Labels: dino-accepted, open-odyssey

#53 Added Messi Fanpage
  Messi-Fanpage/M.png
  Messi-Fanpage/anime.css
  Messi-Fanpage/form.html
  Messi-Fanpage/form_anime.css
  Messi-Fanpage/form_style.css
  Messi-Fanpage/index.html
  Messi-Fanpage/logo.png
  Messi-Fanpage/messi.png
  Messi-Fanpage/messi10.png
  Messi-Fanpage/messiback.jpg
  Messi-Fanpage/messibg.png
  Messi-Fanpage/style.css
Labels: dino-accepted

#58 Added Space_Shooting_Game
  Space_Shooting_Game/Bullet.js
  Space_Shooting_Game/bulletcontroller.js
  Space_Shooting_Game/enemy.js
  Space_Shooting_Game/enemycontroller.js
  Space_Shooting_Game/enemymove.js
  Space_Shooting_Game/images/alien1.png
  Space_Shooting_Game/images/alien10.png
  Space_Shooting_Game/images/alien2.png
  Space_Shooting_Game/images/alien3.png
  Space_Shooting_Game/images/alien4.png
  Space_Shooting_Game/images/alien5.png
  Space_Shooting_Game/images/alien6.png
  Space_Shooting_Game/images/alien7.png
  Space_Shooting_Game/images/alien8.png
  Space_Shooting_Game/images/alien9.png
  Space_Shooting_Game/images/enemyship1.png
  Space_Shooting_Game/images/enemyship2.png
  Space_Shooting_Game/images/ship1.png
  Space_Shooting_Game/images/ship2.png
  Space_Shooting_Game/images/ship3.png
  Space_Shooting_Game/images/ship4.png
  Space_Shooting_Game/images/ship5.png
  Space_Shooting_Game/images/ship6.png
  Space_Shooting_Game/images/ship7.png
  Space_Shooting_Game/images/ship8.png
  Space_Shooting_Game/images/ship9.png
  Space_Shooting_Game/images/space.png
  Space_Shooting_Game/index.html
  Space_Shooting_Game/index.js
  Space_Shooting_Game/player.js
  Space_Shooting_Game/sounds/enemy-death.wav
  Space_Shooting_Game/sounds/shoot.wav
  Space_Shooting_Game/styles.css
Labels: dino-accepted, open-odyssey

#66 deleted ping-pong-game
  ping-pong-game/LICENSE
  ping-pong-game/README.md
  ping-pong-game/Sounds/comScore.mp3
  ping-pong-game/Sounds/hit.mp3
  ping-pong-game/Sounds/userScore.mp3
  ping-pong-game/Sounds/wall.mp3
  ping-pong-game/index.html
  ping-pong-game/pong.js
Labels: invalid

#68 Netflix Clone
  NetflixClone/Astyle.css
  NetflixClone/netflix.html
  NetflixClone/script.js
Labels: dino-accepted

#69 Landing Page & Weather
  Landing Page/Instagram_icon.png.webp
  Landing Page/dyno_997car_s_93.gif
  Landing Page/fb.png
  Landing Page/index.html
  Landing Page/logo (2).png
  Landing Page/pngwing.com.png
  Landing Page/porche back.jpg
  Landing Page/porche front.webp
  Landing Page/porche interior.webp
  Landing Page/porche side.webp
  Landing Page/porsche-911.jpg
  Landing Page/porsche-logo.jpg
  Landing Page/script.js
  Landing Page/slider1.jpg
  Landing Page/styles.css
  Landing Page/x.jpg
  Landing Page/x.png
  Landing Page/x.webp
  Landing Page/yt.png
  Weather/Index.html
  Weather/app.js
  Weather/style.css
Labels: good first issue, dino-accepted, open-odyssey

#70 Simon game
  simongame/app.js
  simongame/cat.jpg
  simongame/catt.png
  simongame/index.html
  simongame/style.css
Labels: dino-accepted

#71 Ping Pong Game
  ping-pong-game/LICENSE
  ping-pong-game/README.md
  ping-pong-game/Sounds/comScore.mp3
  ping-pong-game/Sounds/hit.mp3
  ping-pong-game/Sounds/userScore.mp3
  ping-pong-game/Sounds/wall.mp3
  ping-pong-game/index.html
  ping-pong-game/pong.js
Labels: dino-accepted, open-odyssey

#73 T-Rex Runner
  t-rex-runner/LICENSE
  t-rex-runner/README.md
  t-rex-runner/assets/default_100_percent/100-offline-sprite.png
  t-rex-runner/assets/default_200_percent/200-offline-sprite.png
  t-rex-runner/assets/hello-kugou.gif
  t-rex-runner/assets/kumamon-runner.gif
  t-rex-runner/assets/novas-coisas.gif
  t-rex-runner/assets/offline-sprite-1x.png
  t-rex-runner/assets/offline-sprite-2x.png
  t-rex-runner/index.html
  t-rex-runner/script.js
  t-rex-runner/style.css
Labels: dino-accepted, open-odyssey

#74 Added React Quotes Generator
  React-Quotes-Generator/.gitignore
  React-Quotes-Generator/README.md
  React-Quotes-Generator/package-lock.json
  React-Quotes-Generator/package.json
  React-Quotes-Generator/postcss.config.js
  React-Quotes-Generator/public/favicon.ico
  React-Quotes-Generator/public/index.html
  React-Quotes-Generator/public/logo192.png
  React-Quotes-Generator/public/logo512.png
  React-Quotes-Generator/public/manifest.json
  React-Quotes-Generator/public/robots.txt
  React-Quotes-Generator/src/App.js
  React-Quotes-Generator/src/index.css
  React-Quotes-Generator/src/index.js
  React-Quotes-Generator/src/reportWebVitals.js
  React-Quotes-Generator/tailwind.config.js
Labels: dino-accepted, open-odyssey

#26 Add a Project "React-Typing-Test"
  React-Typing-Test/.gitignore
  React-Typing-Test/README.md
  React-Typing-Test/eslint.config.js
  React-Typing-Test/index.html
  React-Typing-Test/package-lock.json
  React-Typing-Test/package.json
  React-Typing-Test/public/logo.svg
  React-Typing-Test/src/App.jsx
  React-Typing-Test/src/main.jsx
  React-Typing-Test/vite.config.js
Labels: dino-accepted, open-odyssey

#98 Quiz Website
  Quiz website/.vscode/launch.json
  Quiz website/image/OG-image-3.jpg
  Quiz website/index.html
  Quiz website/react.js
  Quiz website/style.css
Labels: open-odyssey

#80 Word Counter
  .vscode/settings.json
  Qr code generator/QR CODE GENERATOR (New).html
  Qr code generator/QR CODE GENERATOR (Old).html
  Qr code generator/QR CODE GENERATOR.html
  Weather/Index.html
  Word-Counter/index.html
  Word-Counter/script.js
  Word-Counter/styles.css
Labels: open-odyssey

#81 Random gif genetator
  React Random gif Generator/.gitignore
  React Random gif Generator/README.md
  React Random gif Generator/package-lock.json
  React Random gif Generator/package.json
  React Random gif Generator/public/index.html
  React Random gif Generator/public/manifest.json
  React Random gif Generator/public/robots.txt
  React Random gif Generator/src/.env
  React Random gif Generator/src/App.css
  React Random gif Generator/src/App.jsx
  React Random gif Generator/src/components/Random.js
  React Random gif Generator/src/components/Tag.js
  React Random gif Generator/src/index.css
  React Random gif Generator/src/index.js
  React Random gif Generator/tailwind.config.js
Labels: open-odyssey

#83 Added React Mind Map Creator
  react-mind-map-creator/.gitignore
  react-mind-map-creator/LICENSE
  react-mind-map-creator/README.md
  react-mind-map-creator/package-lock.json
  react-mind-map-creator/package.json
  react-mind-map-creator/public/favicon.ico
  react-mind-map-creator/public/index.html
  react-mind-map-creator/public/logo192.png
  react-mind-map-creator/public/logo512.png
  react-mind-map-creator/public/manifest.json
  react-mind-map-creator/public/robots.txt
  react-mind-map-creator/src/App.css
  react-mind-map-creator/src/App.js
  react-mind-map-creator/src/App.test.js
  react-mind-map-creator/src/components/FlowControls.js
  react-mind-map-creator/src/components/RichContentNode.js
  react-mind-map-creator/src/components/initialData.js
  react-mind-map-creator/src/components/utils.js
  react-mind-map-creator/src/index.css
  react-mind-map-creator/src/index.js
  react-mind-map-creator/src/logo.svg
  react-mind-map-creator/src/reportWebVitals.js
  react-mind-map-creator/src/setupTests.js
Labels: open-odyssey

#89 Solve issue #46: Add Text To Speech Generator in React
  text-to-speech-generator/.gitignore
  text-to-speech-generator/LICENCE
  text-to-speech-generator/README.md
  text-to-speech-generator/package-lock.json
  text-to-speech-generator/package.json
  text-to-speech-generator/postcss.config.js
  text-to-speech-generator/public/favicon.ico
  text-to-speech-generator/public/index.html
  text-to-speech-generator/public/logo192.png
  text-to-speech-generator/public/logo512.png
  text-to-speech-generator/public/manifest.json
  text-to-speech-generator/public/mic.png
  text-to-speech-generator/public/robots.txt
  text-to-speech-generator/src/App.css
  text-to-speech-generator/src/App.test.tsx
  text-to-speech-generator/src/App.tsx
  text-to-speech-generator/src/components/TextToSpeech.tsx
  text-to-speech-generator/src/components/Voices.tsx
  text-to-speech-generator/src/index.css
  text-to-speech-generator/src/index.tsx
  text-to-speech-generator/src/logo.svg
  text-to-speech-generator/src/react-app-env.d.ts
  text-to-speech-generator/src/reportWebVitals.ts
  text-to-speech-generator/src/setupTests.ts
  text-to-speech-generator/tailwind.config.js
  text-to-speech-generator/tsconfig.json
Labels: open-odyssey

#87 Add Logo maker
  Logo/.eslintrc.cjs
  Logo/.gitignore
  Logo/README.md
  Logo/bun.lockb
  Logo/components.json
  Logo/index.html
  Logo/jsconfig.json
  Logo/package-lock.json
  Logo/package.json
  Logo/postcss.config.js
  Logo/public/logo.png
  Logo/public/vite.svg
  Logo/src/App.css
  Logo/src/App.jsx
  Logo/src/assets/react.svg
  Logo/src/components/BgController.jsx
  Logo/src/components/ColorPickerController.jsx
  Logo/src/components/Header.jsx
  Logo/src/components/IconController.jsx
  Logo/src/components/IconList.jsx
  Logo/src/components/LogoPreview.jsx
  Logo/src/components/SideNav.jsx
  Logo/src/components/ui/button.jsx
  Logo/src/components/ui/dialog.jsx
  Logo/src/components/ui/slider.jsx
  Logo/src/constants/icons.js
  Logo/src/context/UpdateStorageContext.js
  Logo/src/index.css
  Logo/src/lib/utils.js
  Logo/src/main.jsx
  Logo/tailwind.config.js
  Logo/vite.config.js
Labels: open-odyssey

#90 Added Note-taking app
  Note-taking App/index.html
  Note-taking App/script.js
  Note-taking App/style.css
Labels: open-odyssey

#106 Online IDE
  Online IDE/index.html
  Online IDE/script.js
  Online IDE/styles.css
Labels: dino-accepted, open-odyssey

#107 Added Restaurant Website
  RESTAURANT/Capture.JPG
  RESTAURANT/Capture1.JPG
  RESTAURANT/image.png
  RESTAURANT/index.html
  RESTAURANT/style.css
Labels: dino-accepted, open-odyssey

#108 made Stone-paper-Scissors Game using React
  stonepaperScissors-React/.gitignore
  stonepaperScissors-React/README.md
  stonepaperScissors-React/eslint.config.js
  stonepaperScissors-React/index.html
  stonepaperScissors-React/package-lock.json
  stonepaperScissors-React/package.json
  stonepaperScissors-React/postcss.config.js
  stonepaperScissors-React/public/background.jpg
  stonepaperScissors-React/public/paper.png
  stonepaperScissors-React/public/scissors.png
  stonepaperScissors-React/public/stone.png
  stonepaperScissors-React/public/stonepaper.jpg
  stonepaperScissors-React/public/vite.svg
  stonepaperScissors-React/src/App.jsx
  stonepaperScissors-React/src/assets/react.svg
  stonepaperScissors-React/src/index.css
  stonepaperScissors-React/src/main.jsx
  stonepaperScissors-React/tailwind.config.js
  stonepaperScissors-React/vite.config.js
Labels: dino-accepted

#110 The Movie Database App
  movie-database-app/LICENSE
  movie-database-app/README.md
  movie-database-app/index.html
  movie-database-app/script.js
  movie-database-app/style.css
Labels: dino-accepted

#111 Movie
  MOVIE-APPLICATION/README.md
  MOVIE-APPLICATION/movie.css
  MOVIE-APPLICATION/movie.html
  MOVIE-APPLICATION/movie.js
Labels: good first issue, dino-accepted

#113 PR Title: Enhance User Experience: Improved Flexibility and Usability…
  Note-taking App/index.html
  Note-taking App/script.js
  Note-taking App/style.css
Labels: dino-accepted, open-odyssey

#114 Add files via upload
  DSA Website/arrays.html
  DSA Website/dsa.html
  DSA Website/graphs.html
  DSA Website/hashing.html
  DSA Website/heaps.html
  DSA Website/linked-lists.html
  DSA Website/queues.html
  DSA Website/stacks.html
  DSA Website/style.css
  DSA Website/style_landing.css
  DSA Website/trees.html
Labels: dino-accepted, open-odyssey

#116 Add Issues & PR templates
  .github/ISSUE_TEMPLATES/Bug-report.yml
  .github/ISSUE_TEMPLATES/Change-code.yml
  .github/ISSUE_TEMPLATES/Feature-request.yml
  .github/Pull-request.yml
Labels: good first issue, dino-accepted, open-odyssey

#118 Add Files
  Music-WebApp/gift_card.png
  Music-WebApp/hero_image.png
  Music-WebApp/index.html
  Music-WebApp/ipad-iphone.png
  Music-WebApp/mac.png
  Music-WebApp/style.css
  Music-WebApp/video.png
Labels: dino-accepted, open-odyssey

#119 Add DSA Roadmap Application for Structured Learning Path
  DSA-MindMaps/dsa-mindmaps/.gitignore
  DSA-MindMaps/dsa-mindmaps/README.md
  DSA-MindMaps/dsa-mindmaps/package-lock.json
  DSA-MindMaps/dsa-mindmaps/package.json
  DSA-MindMaps/dsa-mindmaps/public/favicon.ico
  DSA-MindMaps/dsa-mindmaps/public/index.html
  DSA-MindMaps/dsa-mindmaps/public/logo192.png
  DSA-MindMaps/dsa-mindmaps/public/logo512.png
  DSA-MindMaps/dsa-mindmaps/public/manifest.json
  DSA-MindMaps/dsa-mindmaps/public/robots.txt
  DSA-MindMaps/dsa-mindmaps/src/App.css
  DSA-MindMaps/dsa-mindmaps/src/App.js
  DSA-MindMaps/dsa-mindmaps/src/App.test.js
  DSA-MindMaps/dsa-mindmaps/src/index.css
  DSA-MindMaps/dsa-mindmaps/src/index.js
  DSA-MindMaps/dsa-mindmaps/src/logo.svg
  DSA-MindMaps/dsa-mindmaps/src/reportWebVitals.js
  DSA-MindMaps/dsa-mindmaps/src/setupTests.js
Labels: dino-accepted, open-odyssey

#125 Added a Recipe Finder
  Recipe finder/index.html
  Recipe finder/script.js
  Recipe finder/style.css
Labels: dino-accepted

#128 Time tracker project & Ticket Managing project
  Countdown- Time tracker/index.html
  Countdown- Time tracker/script.js
  Countdown- Time tracker/style.css
  Ticket Manager/index.html
  Ticket Manager/script.js
  Ticket Manager/station.jpg
  Ticket Manager/style.css
Labels: dino-accepted, open-odyssey

#129 Add Flappy Bird Game with Modern Design and Animations
  Flappy_bird_Game/index.html
  Flappy_bird_Game/script.js
  Flappy_bird_Game/style.css
Labels: dino-accepted

#133 added my project - fullstack blogging application
  Blogging-Application/Readme.md
  Blogging-Application/backend/.gitignore
  Blogging-Application/backend/README.md
  Blogging-Application/backend/package-lock.json
  Blogging-Application/backend/package.json
  Blogging-Application/backend/prisma/migrations/20240828122330_init_schema/migration.sql
  Blogging-Application/backend/prisma/migrations/migration_lock.toml
  Blogging-Application/backend/prisma/schema.prisma
  Blogging-Application/backend/src/index.ts
  Blogging-Application/backend/src/routes/blog.ts
  Blogging-Application/backend/src/routes/user.ts
  Blogging-Application/backend/tsconfig.json
  Blogging-Application/frontend/.gitignore
  Blogging-Application/frontend/README.md
  Blogging-Application/frontend/eslint.config.js
  Blogging-Application/frontend/index.html
  Blogging-Application/frontend/package-lock.json
  Blogging-Application/frontend/package.json
  Blogging-Application/frontend/postcss.config.js
  Blogging-Application/frontend/public/vite.svg
  Blogging-Application/frontend/src/App.css
  Blogging-Application/frontend/src/App.tsx
  Blogging-Application/frontend/src/assets/react.svg
  Blogging-Application/frontend/src/components/Appbar.tsx
  Blogging-Application/frontend/src/components/Auth.tsx
  Blogging-Application/frontend/src/components/BlogCard.tsx
  Blogging-Application/frontend/src/components/FullBlog.tsx
  Blogging-Application/frontend/src/components/ProtectedRoute.tsx
  Blogging-Application/frontend/src/components/Quote.tsx
  Blogging-Application/frontend/src/components/Skeleton.tsx
  Blogging-Application/frontend/src/components/Spinner.tsx
  Blogging-Application/frontend/src/config.ts
  Blogging-Application/frontend/src/hooks/index.ts
  Blogging-Application/frontend/src/index.css
  Blogging-Application/frontend/src/main.tsx
  Blogging-Application/frontend/src/pages/Blog.tsx
  Blogging-Application/frontend/src/pages/Blogs.tsx
  Blogging-Application/frontend/src/pages/Publish.tsx
  Blogging-Application/frontend/src/pages/Signin.tsx
  Blogging-Application/frontend/src/pages/Signup.tsx
  Blogging-Application/frontend/src/vite-env.d.ts
  Blogging-Application/frontend/tailwind.config.js
  Blogging-Application/frontend/tsconfig.app.json
  Blogging-Application/frontend/tsconfig.json
  Blogging-Application/frontend/tsconfig.node.json
  Blogging-Application/frontend/vercel.json
  Blogging-Application/frontend/vite.config.ts
Labels: dino-accepted, open-odyssey

#135 Added Reactjs-to-do (#131)
  Reactjs-To-do /.gitignore
  Reactjs-To-do /README.md
  Reactjs-To-do /eslint.config.js
  Reactjs-To-do /index.html
  Reactjs-To-do /package.json
  Reactjs-To-do /postcss.config.js
  Reactjs-To-do /public/vite.svg
  Reactjs-To-do /src/App.css
  Reactjs-To-do /src/App.jsx
  Reactjs-To-do /src/assets/react.svg
  Reactjs-To-do /src/components/Navbar.jsx
  Reactjs-To-do /src/index.css
  Reactjs-To-do /src/main.jsx
  Reactjs-To-do /tailwind.config.js
  Reactjs-To-do /vite.config.js
Labels: dino-accepted

#136 created a piano game
  Piano_master/index.html
  Piano_master/notes/A.mp3
  Piano_master/notes/Ab.mp3
  Piano_master/notes/B.mp3
  Piano_master/notes/Bb.mp3
  Piano_master/notes/C.mp3
  Piano_master/notes/D.mp3
  Piano_master/notes/Db.mp3
  Piano_master/notes/E.mp3
  Piano_master/notes/Eb.mp3
  Piano_master/notes/F.mp3
  Piano_master/notes/G.mp3
  Piano_master/notes/Gb.mp3
  Piano_master/piano_game.md
  Piano_master/script.js
  Piano_master/styles.css
Labels: dino-accepted, open-odyssey

#137 Created iDragon Adventures - JavaScript Game
  JavaScript Dragon Game/bg.png
  JavaScript Dragon Game/dino.png
  JavaScript Dragon Game/dragon.png
  JavaScript Dragon Game/gameover.mp3
  JavaScript Dragon Game/index.html
  JavaScript Dragon Game/music.mp3
  JavaScript Dragon Game/script.js
  JavaScript Dragon Game/style.css
  JavaScript Dragon Game/tutorials.md
Labels: dino-accepted, open-odyssey

#140 Emoji Catcher Game
  Emoji Catcher Game/app.js
  Emoji Catcher Game/index.html
  Emoji Catcher Game/style.css
Labels: dino-accepted

#141 Added Reactjs-photshop-clone
  Reactjs-photoshop-clone/.gitignore
  Reactjs-photoshop-clone/README.md
  Reactjs-photoshop-clone/eslint.config.js
  Reactjs-photoshop-clone/index.html
  Reactjs-photoshop-clone/package.json
  Reactjs-photoshop-clone/src/App.css
  Reactjs-photoshop-clone/src/App.jsx
  Reactjs-photoshop-clone/src/SidebarItem.jsx
  Reactjs-photoshop-clone/src/Slider.jsx
  Reactjs-photoshop-clone/src/main.jsx
  Reactjs-photoshop-clone/vite.config.js
Labels: dino-accepted

#144 Rename Readme.txt to Readme.md
  Online-Library-Management-System-PHP/Readme.md
Labels: invalid, open-odyssey

#152 Readded React-todo
  Reactjs-To-do/.gitignore
  Reactjs-To-do/README.md
  Reactjs-To-do/eslint.config.js
  Reactjs-To-do/index.html
  Reactjs-To-do/package.json
  Reactjs-To-do/postcss.config.js
  Reactjs-To-do/public/vite.svg
  Reactjs-To-do/src/App.css
  Reactjs-To-do/src/App.jsx
  Reactjs-To-do/src/assets/react.svg
  Reactjs-To-do/src/components/Navbar.jsx
  Reactjs-To-do/src/index.css
  Reactjs-To-do/src/main.jsx
  Reactjs-To-do/tailwind.config.js
  Reactjs-To-do/vite.config.js
Labels: dino-accepted, open-odyssey

#154 Added Bubble shooter game
  Bubble-Shooter Game/bubble-shooter-example.js
  Bubble-Shooter Game/bubble-shooter.html
  Bubble-Shooter Game/bubble-sprites.png
  Bubble-Shooter Game/screenshot.png
Labels: dino-accepted, open-odyssey

#155 Shape Clicker Game
  Shape Clicker Game/app.js
  Shape Clicker Game/index.html
  Shape Clicker Game/readme.md
  Shape Clicker Game/style.css
Labels: dino-accepted, open-odyssey

#153 Live Code Editor
  Live Code Editor/README.md
  Live Code Editor/app.js
  Live Code Editor/index.html
  Live Code Editor/main.css
Labels: dino-accepted, open-odyssey

#156 Typing Game is added
  Typing Game/app.js
  Typing Game/index.html
  Typing Game/readme.md
  Typing Game/style.css
Labels: dino-accepted, open-odyssey

#157 Space-Invaders is added
  Space Invaders/Play-Regular.ttf
  Space Invaders/index.html
  Space Invaders/readme.md
  Space Invaders/script.js
  Space Invaders/sprite_.png
  Space Invaders/style.css
Labels: dino-accepted, open-odyssey

#159 Lost Path- The maze game is added
  Lost Path/index.html
  Lost Path/readme.md
Labels: dino-accepted, open-odyssey

#160 Ludo King game
  Ludo King/Images/1.jpg
  Ludo King/Images/2.jpg
  Ludo King/Images/3.jpg
  Ludo King/Images/4.jpg
  Ludo King/Images/5.jpg
  Ludo King/Images/6.jpg
  Ludo King/Images/board.gif
  Ludo King/Images/dice.gif
  Ludo King/Ludo-game.html
  Ludo King/Ludo-game.js
  Ludo King/readme.md
Labels: dino-accepted, open-odyssey

#162 3D Restaurant Menu
  3D Restaurant Menu/css/demo.css
  3D Restaurant Menu/css/font/LICENSE.txt
  3D Restaurant Menu/css/font/README.txt
  3D Restaurant Menu/css/font/entypo-selected.eot
  3D Restaurant Menu/css/font/entypo-selected.svg
  3D Restaurant Menu/css/font/entypo-selected.ttf
  3D Restaurant Menu/css/font/entypo-selected.woff
  3D Restaurant Menu/css/normalize.css
  3D Restaurant Menu/css/style.css
  3D Restaurant Menu/images/1.jpg
  3D Restaurant Menu/images/10.jpg
  3D Restaurant Menu/images/11.jpg
  3D Restaurant Menu/images/12.jpg
  3D Restaurant Menu/images/13.jpg
  3D Restaurant Menu/images/14.jpg
  3D Restaurant Menu/images/2.jpg
  3D Restaurant Menu/images/3.jpg
  3D Restaurant Menu/images/4.jpg
  3D Restaurant Menu/images/5.jpg
  3D Restaurant Menu/images/6.jpg
  3D Restaurant Menu/images/7.jpg
  3D Restaurant Menu/images/8.jpg
  3D Restaurant Menu/images/9.jpg
  3D Restaurant Menu/images/bg.jpg
  3D Restaurant Menu/images/restaurant.jpg
  3D Restaurant Menu/images/white_paperboard.jpg
  3D Restaurant Menu/index.html
  3D Restaurant Menu/js/menu.js
  3D Restaurant Menu/js/modernizr.custom.79639.js
Labels: dino-accepted, open-odyssey

#165 First person shooting Game is added
  First Person Shooter Game/Bullets.js
  First Person Shooter Game/Crosshair.js
  First Person Shooter Game/Enemies.js
  First Person Shooter Game/Map.js
  First Person Shooter Game/Skybox.js
  First Person Shooter Game/TheScene.js
  First Person Shooter Game/avatar.js
  First Person Shooter Game/imgs/Skybox/bk.JPG
  First Person Shooter Game/imgs/Skybox/dn.JPG
  First Person Shooter Game/imgs/Skybox/ft.JPG
  First Person Shooter Game/imgs/Skybox/lf.JPG
  First Person Shooter Game/imgs/Skybox/rt.JPG
  First Person Shooter Game/imgs/Skybox/up.JPG
  First Person Shooter Game/imgs/bullettext.jpg
  First Person Shooter Game/imgs/diana.png
  First Person Shooter Game/imgs/metal.jpg
  First Person Shooter Game/imgs/piedras.jpg
  First Person Shooter Game/imgs/wood.jpg
  First Person Shooter Game/index.html
  First Person Shooter Game/libs/MTLLoader.js
  First Person Shooter Game/libs/OBJLoader.js
  First Person Shooter Game/libs/PointerLockControls.js
  First Person Shooter Game/libs/ammo.js
  First Person Shooter Game/libs/dat.gui.js
  First Person Shooter Game/libs/howler.js
  First Person Shooter Game/libs/jquery-1.9.0.js
  First Person Shooter Game/libs/physi.js
  First Person Shooter Game/libs/physijs_worker.js
  First Person Shooter Game/libs/stats.js
  First Person Shooter Game/libs/three.js
  First Person Shooter Game/models/escopeta.obj
  First Person Shooter Game/models/escopetatext.png
  First Person Shooter Game/models/m4a1_s.obj
  First Person Shooter Game/models/m4a1_stext.png
  First Person Shooter Game/models/material.mtl
  First Person Shooter Game/script.js
  First Person Shooter Game/sounds/animals020.mp3
  First Person Shooter Game/sounds/death.mp3
  First Person Shooter Game/sounds/escopeta.mp3
  First Person Shooter Game/sounds/m4a1_s.mp3
Labels: dino-accepted, open-odyssey

#168 added BeatNest
  beatnest/.eslintrc.json
  beatnest/.gitignore
  beatnest/README.md
  beatnest/app/favicon.ico
  beatnest/app/fonts/GeistMonoVF.woff
  beatnest/app/fonts/GeistVF.woff
  beatnest/app/globals.css
  beatnest/app/layout.tsx
  beatnest/app/page.tsx
  beatnest/app/play/page.tsx
  beatnest/components.json
  beatnest/components/ui/button.tsx
  beatnest/components/ui/sparkles.tsx
  beatnest/lib/utils.ts
  beatnest/next.config.mjs
  beatnest/package-lock.json
  beatnest/package.json
  beatnest/postcss.config.mjs
  beatnest/tailwind.config.ts
  beatnest/tsconfig.json
Labels: dino-accepted, open-odyssey

#169 Updated Temperature Convertor
  Temperature Convertor/index.html
  Temperature Convertor/script.js
  Temperature Convertor/style.css
Labels: dino-accepted, open-odyssey

#170 Added my To Do List project @priyo
  To do List/Background.jpeg
  To do List/index.html
  To do List/script.js
  To do List/style.css
Labels: dino-accepted, open-odyssey

#172 Added Flag game
  Flag project/datas/levels.txt
  Flag project/icons/background.jpg
  Flag project/icons/background.webp
  Flag project/icons/flags-logo.png
  Flag project/icons/logo.png
  Flag project/index.html
  Flag project/script.js
  Flag project/style.css
Labels: dino-accepted, open-odyssey

#174 StopWatch
  Stop Watch/index.html
  Stop Watch/index.js
  Stop Watch/style.css
Labels: dino-accepted, open-odyssey

#175 Text To Qr Genarator
  Text To Qr Genarator/index.html
  Text To Qr Genarator/script.js
  Text To Qr Genarator/style.css
Labels: dino-accepted, open-odyssey

#167 Whack-A-Mole Game
  Whack A Mole/dirt.svg
  Whack A Mole/index.html
  Whack A Mole/mole.svg
  Whack A Mole/readme.md
  Whack A Mole/style.css
Labels: dino-accepted, open-odyssey

#166 Penalty Shootout Game
  Penalty Shootout Game/css/main.css
  Penalty Shootout Game/css/normalize.css
  Penalty Shootout Game/css/normalize.min.css
  Penalty Shootout Game/img/background.jpg
  Penalty Shootout Game/img/direction-horizontal.png
  Penalty Shootout Game/img/direction-vertical.png
  Penalty Shootout Game/img/favicons/zee-ball-16x16.png
  Penalty Shootout Game/img/favicons/zee-ball-43x43.png
  Penalty Shootout Game/img/form.jpg
  Penalty Shootout Game/img/instructions.jpg
  Penalty Shootout Game/img/keeper-left-jump.png
  Penalty Shootout Game/img/keeper-right-jump.png
  Penalty Shootout Game/img/keeper-standing.png
  Penalty Shootout Game/img/like-gate.jpg
  Penalty Shootout Game/img/power.png
  Penalty Shootout Game/img/slow-kick-right.png
  Penalty Shootout Game/img/small-ball.png
  Penalty Shootout Game/img/splash-screen.jpg
  Penalty Shootout Game/img/zee-ball.png
  Penalty Shootout Game/index.html
  Penalty Shootout Game/js/.main.js.swp
  Penalty Shootout Game/js/main.js
  Penalty Shootout Game/js/plugins.js
  Penalty Shootout Game/js/vendor/jquery-1.11.0.min.js
  Penalty Shootout Game/js/vendor/modernizr-2.6.2.min.js
  Penalty Shootout Game/js/vendor/pathAnimator.js
Labels: dino-accepted, open-odyssey

#178 added a new virtual Keyboard
  Virtual Keyboard/file.html
Labels: dino-accepted, open-odyssey

#180 added Image Comparison Slider
  image-comparison-slider/LICENSE
  image-comparison-slider/README.md
  image-comparison-slider/index.html
  image-comparison-slider/script.js
  image-comparison-slider/styles.css
Labels: dino-accepted, open-odyssey

#181 added Timetable Generator
  timetable-generator/LICENSE
  timetable-generator/README.md
  timetable-generator/index.html
  timetable-generator/script.js
  timetable-generator/styles.css
Labels: dino-accepted, open-odyssey

#182 added Badge Generator
  badge-generator/LICENSE
  badge-generator/README.md
  badge-generator/index.html
  badge-generator/script.js
  badge-generator/styles.css
Labels: dino-accepted, open-odyssey

#183 added Animated Business Card
  business-card/LICENSE
  business-card/README.md
  business-card/avataaars.png
  business-card/index.html
  business-card/styles.css
Labels: dino-accepted, open-odyssey

#184 Morse Man (Morse x HangMan)
  morse_man/assets/favicon/android-chrome-192x192.png
  morse_man/assets/favicon/android-chrome-512x512.png
  morse_man/assets/favicon/apple-touch-icon.png
  morse_man/assets/favicon/favicon-16x16.png
  morse_man/assets/favicon/favicon-32x32.png
  morse_man/assets/favicon/favicon.ico
  morse_man/assets/favicon/site.webmanifest
  morse_man/assets/fonts/Px437_Acer710_Mono.ttf
  morse_man/assets/js/alphabetToMorse.js
  morse_man/assets/sounds/dash.wav
  morse_man/assets/sounds/dot.wav
  morse_man/assets/sounds/static-pixabay.mp3
  morse_man/assets/videos/757C.gif
  morse_man/index.html
  morse_man/index.js
  morse_man/style.css
Labels: dino-accepted, open-odyssey

#185 Weather Locator
  Weather Locator/assets/404.png
  Weather Locator/assets/clear.png
  Weather Locator/assets/cloud.png
  Weather Locator/assets/mist.png
  Weather Locator/assets/rain.png
  Weather Locator/assets/snow.png
  Weather Locator/index.html
  Weather Locator/script.js
  Weather Locator/style.css
Labels: dino-accepted, open-odyssey

#186 added Virtual Pop-it Fidget Toy
  virtual-popit/LICENSE
  virtual-popit/README.md
  virtual-popit/image.png
  virtual-popit/index.html
  virtual-popit/pop_sound.mp3
  virtual-popit/script.js
  virtual-popit/styles.css
Labels: dino-accepted, open-odyssey

#187 added Virtual Piano
  virtual-piano/LICENSE
  virtual-piano/README.md
  virtual-piano/index.html
  virtual-piano/script.js
  virtual-piano/style.css
  virtual-piano/tunes/;.wav
  virtual-piano/tunes/a.wav
  virtual-piano/tunes/d.wav
  virtual-piano/tunes/e.wav
  virtual-piano/tunes/f.wav
  virtual-piano/tunes/g.wav
  virtual-piano/tunes/h.wav
  virtual-piano/tunes/j.wav
  virtual-piano/tunes/k.wav
  virtual-piano/tunes/l.wav
  virtual-piano/tunes/o.wav
  virtual-piano/tunes/p.wav
  virtual-piano/tunes/s.wav
  virtual-piano/tunes/t.wav
  virtual-piano/tunes/u.wav
  virtual-piano/tunes/w.wav
  virtual-piano/tunes/y.wav
Labels: dino-accepted, open-odyssey

#124 Contribute my project "CodeAura"
  CodeAura/README.md
  CodeAura/backend/app.js
  CodeAura/backend/bin/www
  CodeAura/backend/models/projectModel.js
  CodeAura/backend/models/userModel.js
  CodeAura/backend/package-lock.json
  CodeAura/backend/package.json
  CodeAura/backend/public/stylesheets/style.css
  CodeAura/backend/routes/index.js
  CodeAura/backend/routes/users.js
  CodeAura/backend/views/error.ejs
  CodeAura/backend/views/index.ejs
  CodeAura/frontend/.gitignore
  CodeAura/frontend/README.md
  CodeAura/frontend/eslint.config.js
  CodeAura/frontend/index.html
  CodeAura/frontend/package-lock.json
  CodeAura/frontend/package.json
  CodeAura/frontend/postcss.config.js
  CodeAura/frontend/public/vite.svg
  CodeAura/frontend/src/App.css
  CodeAura/frontend/src/App.jsx
  CodeAura/frontend/src/components/EditiorNavbar.jsx
  CodeAura/frontend/src/components/GridCard.jsx
  CodeAura/frontend/src/components/ListCard.jsx
  CodeAura/frontend/src/components/Navbar.jsx
  CodeAura/frontend/src/helper.js
  CodeAura/frontend/src/images/authPageSide.png
  CodeAura/frontend/src/images/code.png
  CodeAura/frontend/src/images/delete.png
  CodeAura/frontend/src/images/logo.png
  CodeAura/frontend/src/index.css
  CodeAura/frontend/src/main.jsx
  CodeAura/frontend/src/pages/Editior.jsx
  CodeAura/frontend/src/pages/Home.jsx
  CodeAura/frontend/src/pages/Login.jsx
  CodeAura/frontend/src/pages/NoPage.jsx
  CodeAura/frontend/src/pages/SignUp.jsx
  CodeAura/frontend/tailwind.config.js
  CodeAura/frontend/vite.config.js
Labels: dino-accepted, open-odyssey

#188 added Easy Image Editor
  easy-image-editor/LICENSE
  easy-image-editor/README.md
  easy-image-editor/image-placeholder.svg
  easy-image-editor/index.html
  easy-image-editor/script.js
  easy-image-editor/style.css
Labels: dino-accepted, open-odyssey

#198 adding a new gita explorer wesbite
  Gita explorer/index.html
  Gita explorer/script.js
  Gita explorer/stories.html
  Gita explorer/stories.js
  Gita explorer/styles.css
  calender/index.html
Labels: dino-accepted, open-odyssey

#191 added Loan Calculator
  loan-calculator/LICENSE
  loan-calculator/README.md
  loan-calculator/index.html
  loan-calculator/style.css
Labels: dino-accepted, open-odyssey

#189 added Speed Typing Test
  speed-typing-test/LICENSE
  speed-typing-test/README.md
  speed-typing-test/index.html
  speed-typing-test/style.css
  speed-typing-test/test.js
Labels: dino-accepted, open-odyssey

#190 added Dictionary Web App
  dictionary-web-app/LICENSE
  dictionary-web-app/README.md
  dictionary-web-app/index.html
  dictionary-web-app/script.js
  dictionary-web-app/style.css
Labels: dino-accepted, open-odyssey

#192 To-Do App
  To-Do App/To-Do App Description.md
  To-Do App/images/checked.png
  To-Do App/images/icon.png
  To-Do App/images/unchecked.png
  To-Do App/index.html
  To-Do App/script.js
  To-Do App/style.css
Labels: dino-accepted, open-odyssey

#193 Virtual Keyboard Project
  Virtual Keyboard/file.html
  Virtual Keyboard/sounds/keypress-sound.mp3
Labels: dino-accepted, open-odyssey

#194 Added a Flask todo-app
  flask-todo-app/Readme.md
  flask-todo-app/screenshots/Screenshot1.png
  flask-todo-app/src/app.py
  flask-todo-app/src/instance/todos.db
  flask-todo-app/src/templates/index.html
Labels: dino-accepted, open-odyssey

#195 8 Puzzle game
  8 Puzzle/README.md
  8 Puzzle/index.html
Labels: dino-accepted, open-odyssey

#199 Added my Finance Tracker project @priyo
  Finance Tracker/index.html
  Finance Tracker/index.js
  Finance Tracker/style.css
  Timeline/tree.html
Labels: dino-accepted, open-odyssey

#200 Landing page - Denytech
  BarberShop Frontend Design/img/banner.jpg
  BarberShop Frontend Design/img/barber-man.jpg
  BarberShop Frontend Design/img/close.png
  BarberShop Frontend Design/img/facebook.svg
  BarberShop Frontend Design/img/footer-img.png
  BarberShop Frontend Design/img/img-1.jpg
  BarberShop Frontend Design/img/img-2.jpg
  BarberShop Frontend Design/img/img-3.jpg
  BarberShop Frontend Design/img/instagram.svg
  BarberShop Frontend Design/img/logo.png
  BarberShop Frontend Design/img/logo1.jpg
  BarberShop Frontend Design/img/logo2.png
  BarberShop Frontend Design/img/logo3.png
  BarberShop Frontend Design/img/menu.png
  BarberShop Frontend Design/img/pic-1.jpg
  BarberShop Frontend Design/img/pic-2.jpg
  BarberShop Frontend Design/img/pic-3.jpg
  BarberShop Frontend Design/img/pic-4.jpg
  BarberShop Frontend Design/img/twitter.svg
  BarberShop Frontend Design/index.html
  BarberShop Frontend Design/style.css
  LandinPage-Denytech/index.html
  LandinPage-Denytech/style.css
Labels: dino-accepted, open-odyssey

#281 added CSS Filter Funhouse
  css-filter-funhouse/LICENSE
  css-filter-funhouse/README.md
  css-filter-funhouse/index.html
  css-filter-funhouse/script.js
  css-filter-funhouse/style.css
Labels: dino-accepted, open-odyssey

#282 Added Close Quarter Combat game in React JS
  close-quarter-combat/.gitignore
  close-quarter-combat/package-lock.json
  close-quarter-combat/package.json
  close-quarter-combat/public/favicon.ico
  close-quarter-combat/public/game/cqcupdated.swf
  close-quarter-combat/public/index.html
  close-quarter-combat/public/logo192.png
  close-quarter-combat/public/logo512.png
  close-quarter-combat/public/manifest.json
  close-quarter-combat/public/robots.txt
  close-quarter-combat/src/App.css
  close-quarter-combat/src/App.js
  close-quarter-combat/src/App.test.js
  close-quarter-combat/src/components/GamePlayer.css
  close-quarter-combat/src/components/GamePlayer.js
  close-quarter-combat/src/index.css
  close-quarter-combat/src/index.js
  close-quarter-combat/src/logo.svg
  close-quarter-combat/src/reportWebVitals.js
  close-quarter-combat/src/setupTests.js
Labels: dino-accepted, open-odyssey

#284 added TypeScript Interface Architect
  typescript-interface-architect/LICENSE
  typescript-interface-architect/README.md
  typescript-interface-architect/index.html
  typescript-interface-architect/levels.ts
  typescript-interface-architect/script.js
  typescript-interface-architect/style.css
Labels: dino-accepted, open-odyssey

#285 Added Connect It game in React JS
  connect-it/.gitignore
  connect-it/package-lock.json
  connect-it/package.json
  connect-it/public/favicon.ico
  connect-it/public/game/ConnectIt.swf
  connect-it/public/index.html
  connect-it/public/logo192.png
  connect-it/public/logo512.png
  connect-it/public/manifest.json
  connect-it/public/robots.txt
  connect-it/src/App.css
  connect-it/src/App.js
  connect-it/src/App.test.js
  connect-it/src/components/GamePlayer.css
  connect-it/src/components/GamePlayer.js
  connect-it/src/index.css
  connect-it/src/index.js
  connect-it/src/logo.svg
  connect-it/src/reportWebVitals.js
  connect-it/src/setupTests.js
Labels: dino-accepted, open-odyssey

#288 added CSS Animation Synchronizer
  css-animation-synchronizer/LICENSE
  css-animation-synchronizer/README.md
  css-animation-synchronizer/index.html
  css-animation-synchronizer/script.js
  css-animation-synchronizer/style.css
Labels: dino-accepted, open-odyssey

#289 Added Crimson Room game in React JS
  crimson-room/.gitignore
  crimson-room/package-lock.json
  crimson-room/package.json
  crimson-room/public/favicon.ico
  crimson-room/public/game/andkon617.swf
  crimson-room/public/index.html
  crimson-room/public/logo192.png
  crimson-room/public/logo512.png
  crimson-room/public/manifest.json
  crimson-room/public/robots.txt
  crimson-room/src/App.css
  crimson-room/src/App.js
  crimson-room/src/App.test.js
  crimson-room/src/components/GamePlayer.css
  crimson-room/src/components/GamePlayer.js
  crimson-room/src/index.css
  crimson-room/src/index.js
  crimson-room/src/logo.svg
  crimson-room/src/reportWebVitals.js
  crimson-room/src/setupTests.js
Labels: dino-accepted, open-odyssey

#290 added JavaScript Promise Playground
  promise-playground/LICENSE
  promise-playground/README.md
  promise-playground/index.html
  promise-playground/scripts.js
  promise-playground/styles.css
Labels: dino-accepted, open-odyssey

#291 Added Crimson Warfare game in React JS
  crimson-warfare/.gitignore
  crimson-warfare/package-lock.json
  crimson-warfare/package.json
  crimson-warfare/public/favicon.ico
  crimson-warfare/public/game/rts202c.swf
  crimson-warfare/public/index.html
  crimson-warfare/public/logo192.png
  crimson-warfare/public/logo512.png
  crimson-warfare/public/manifest.json
  crimson-warfare/public/robots.txt
  crimson-warfare/src/App.css
  crimson-warfare/src/App.js
  crimson-warfare/src/App.test.js
  crimson-warfare/src/components/GamePlayer.css
  crimson-warfare/src/components/GamePlayer.js
  crimson-warfare/src/index.css
  crimson-warfare/src/index.js
  crimson-warfare/src/logo.svg
  crimson-warfare/src/reportWebVitals.js
  crimson-warfare/src/setupTests.js
Labels: dino-accepted, open-odyssey

#292 added svelte-reactive-state-mastery
  svelte-reactive-state-mastery/.gitignore
  svelte-reactive-state-mastery/README.md
  svelte-reactive-state-mastery/index.html
  svelte-reactive-state-mastery/jsconfig.json
  svelte-reactive-state-mastery/package-lock.json
  svelte-reactive-state-mastery/package.json
  svelte-reactive-state-mastery/public/index.html
  svelte-reactive-state-mastery/public/vite.svg
  svelte-reactive-state-mastery/src/App.svelte
  svelte-reactive-state-mastery/src/app.css
  svelte-reactive-state-mastery/src/assets/svelte.svg
  svelte-reactive-state-mastery/src/components/Counter.svelte
  svelte-reactive-state-mastery/src/components/Scoreboard.svelte
  svelte-reactive-state-mastery/src/components/Timer.svelte
  svelte-reactive-state-mastery/src/lib/Counter.svelte
  svelte-reactive-state-mastery/src/main.js
  svelte-reactive-state-mastery/src/vite-env.d.ts
  svelte-reactive-state-mastery/svelte.config.js
  svelte-reactive-state-mastery/vite.config.js
Labels: dino-accepted, open-odyssey

#293 added Node API Builder
  node-api-builder/README.md
  node-api-builder/index.js
  node-api-builder/package-lock.json
  node-api-builder/package.json
Labels: dino-accepted, open-odyssey

#294 Added GROW Island game in React JS
  grow-island/.gitignore
  grow-island/package-lock.json
  grow-island/package.json
  grow-island/public/favicon.ico
  grow-island/public/game/growisland.swf
  grow-island/public/index.html
  grow-island/public/logo192.png
  grow-island/public/logo512.png
  grow-island/public/manifest.json
  grow-island/public/robots.txt
  grow-island/src/App.css
  grow-island/src/App.js
  grow-island/src/App.test.js
  grow-island/src/components/GamePlayer.css
  grow-island/src/components/GamePlayer.js
  grow-island/src/index.css
  grow-island/src/index.js
  grow-island/src/logo.svg
  grow-island/src/reportWebVitals.js
  grow-island/src/setupTests.js
Labels: dino-accepted, open-odyssey

#296 added Webpack Config Wizard
  webpack-config-wizard/README.md
  webpack-config-wizard/dist/index.html
  webpack-config-wizard/package.json
  webpack-config-wizard/src/index.js
  webpack-config-wizard/src/styles.css
  webpack-config-wizard/webpack.config.js
Labels: dino-accepted, open-odyssey

#297 Added Indestructotank! 2 game in React JS
  indestructotank-2/.gitignore
  indestructotank-2/package-lock.json
  indestructotank-2/package.json
  indestructotank-2/public/favicon.ico
  indestructotank-2/public/game/indestruc2tank.swf
  indestructotank-2/public/index.html
  indestructotank-2/public/logo192.png
  indestructotank-2/public/logo512.png
  indestructotank-2/public/manifest.json
  indestructotank-2/public/robots.txt
  indestructotank-2/src/App.css
  indestructotank-2/src/App.js
  indestructotank-2/src/App.test.js
  indestructotank-2/src/components/GamePlayer.css
  indestructotank-2/src/components/GamePlayer.js
  indestructotank-2/src/index.css
  indestructotank-2/src/index.js
  indestructotank-2/src/logo.svg
  indestructotank-2/src/reportWebVitals.js
  indestructotank-2/src/setupTests.js
Labels: dino-accepted, open-odyssey

#298 added GraphQL Schema Sculptor
  graphql-schema-sculptor/client/index.html
  graphql-schema-sculptor/client/scrpt.js
  graphql-schema-sculptor/client/style.css
  graphql-schema-sculptor/package-lock.json
  graphql-schema-sculptor/package.json
  graphql-schema-sculptor/server/index.js
  graphql-schema-sculptor/server/schema.js
Labels: dino-accepted, open-odyssey

#299 Added Boxhead: 2Play Rooms game in React JS
  boxhead-2play-rooms/.gitignore
  boxhead-2play-rooms/package-lock.json
  boxhead-2play-rooms/package.json
  boxhead-2play-rooms/public/favicon.ico
  boxhead-2play-rooms/public/game/boxhead2play.swf
  boxhead-2play-rooms/public/index.html
  boxhead-2play-rooms/public/logo192.png
  boxhead-2play-rooms/public/logo512.png
  boxhead-2play-rooms/public/manifest.json
  boxhead-2play-rooms/public/robots.txt
  boxhead-2play-rooms/src/App.css
  boxhead-2play-rooms/src/App.js
  boxhead-2play-rooms/src/App.test.js
  boxhead-2play-rooms/src/components/GamePlayer.css
  boxhead-2play-rooms/src/components/GamePlayer.js
  boxhead-2play-rooms/src/index.css
  boxhead-2play-rooms/src/index.js
  boxhead-2play-rooms/src/logo.svg
  boxhead-2play-rooms/src/reportWebVitals.js
  boxhead-2play-rooms/src/setupTests.js
Labels: dino-accepted, open-odyssey

#300 added CSS Houdini Effects Workshop
  css-houdini-workshop/LICENSE
  css-houdini-workshop/README.md
  css-houdini-workshop/index.html
  css-houdini-workshop/paint.js
  css-houdini-workshop/script.js
  css-houdini-workshop/style.css
Labels: dino-accepted, open-odyssey

#301 Added Boxhead: The Rooms game in React JS
  boxhead-the-rooms/.gitignore
  boxhead-the-rooms/package-lock.json
  boxhead-the-rooms/package.json
  boxhead-the-rooms/public/favicon.ico
  boxhead-the-rooms/public/game/boxheadrooms.swf
  boxhead-the-rooms/public/index.html
  boxhead-the-rooms/public/logo192.png
  boxhead-the-rooms/public/logo512.png
  boxhead-the-rooms/public/manifest.json
  boxhead-the-rooms/public/robots.txt
  boxhead-the-rooms/src/App.css
  boxhead-the-rooms/src/App.js
  boxhead-the-rooms/src/App.test.js
  boxhead-the-rooms/src/components/GamePlayer.css
  boxhead-the-rooms/src/components/GamePlayer.js
  boxhead-the-rooms/src/index.css
  boxhead-the-rooms/src/index.js
  boxhead-the-rooms/src/logo.svg
  boxhead-the-rooms/src/reportWebVitals.js
  boxhead-the-rooms/src/setupTests.js
Labels: dino-accepted, open-odyssey

#302 Added Boxhead: More Rooms game in React JS
  boxhead-more-rooms/.gitignore
  boxhead-more-rooms/package-lock.json
  boxhead-more-rooms/package.json
  boxhead-more-rooms/public/favicon.ico
  boxhead-more-rooms/public/game/boxheadmorerooms.swf
  boxhead-more-rooms/public/index.html
  boxhead-more-rooms/public/logo192.png
  boxhead-more-rooms/public/logo512.png
  boxhead-more-rooms/public/manifest.json
  boxhead-more-rooms/public/robots.txt
  boxhead-more-rooms/src/App.css
  boxhead-more-rooms/src/App.js
  boxhead-more-rooms/src/App.test.js
  boxhead-more-rooms/src/components/GamePlayer.css
  boxhead-more-rooms/src/components/GamePlayer.js
  boxhead-more-rooms/src/index.css
  boxhead-more-rooms/src/index.js
  boxhead-more-rooms/src/logo.svg
  boxhead-more-rooms/src/reportWebVitals.js
  boxhead-more-rooms/src/setupTests.js
Labels: dino-accepted, open-odyssey

#303 Added Indestructotank Anniversary Edition game in React JS
  indestructotank-anniversary-edition/.gitignore
  indestructotank-anniversary-edition/package-lock.json
  indestructotank-anniversary-edition/package.json
  indestructotank-anniversary-edition/public/favicon.ico
  indestructotank-anniversary-edition/public/game/indestructotank.swf
  indestructotank-anniversary-edition/public/index.html
  indestructotank-anniversary-edition/public/logo192.png
  indestructotank-anniversary-edition/public/logo512.png
  indestructotank-anniversary-edition/public/manifest.json
  indestructotank-anniversary-edition/public/robots.txt
  indestructotank-anniversary-edition/src/App.css
  indestructotank-anniversary-edition/src/App.js
  indestructotank-anniversary-edition/src/App.test.js
  indestructotank-anniversary-edition/src/components/GamePlayer.css
  indestructotank-anniversary-edition/src/components/GamePlayer.js
  indestructotank-anniversary-edition/src/index.css
  indestructotank-anniversary-edition/src/index.js
  indestructotank-anniversary-edition/src/logo.svg
  indestructotank-anniversary-edition/src/reportWebVitals.js
  indestructotank-anniversary-edition/src/setupTests.js
Labels: dino-accepted, open-odyssey

#306 CATCHING GAME
  Catching Game/index.html
Labels: dino-accepted, open-odyssey

#307 Build Resume
  resume-builder/image1.png
  resume-builder/image2.png
  resume-builder/index.html
  resume-builder/script.js
Labels: dino-accepted, open-odyssey

#311 feat: add react weather app
  ReactWeatherApp/.gitignore
  ReactWeatherApp/README.md
  ReactWeatherApp/package-lock.json
  ReactWeatherApp/package.json
  ReactWeatherApp/public/favicon.ico
  ReactWeatherApp/public/images/1.png
  ReactWeatherApp/public/images/2.png
  ReactWeatherApp/public/images/3.png
  ReactWeatherApp/public/images/4.png
  ReactWeatherApp/public/images/5.png
  ReactWeatherApp/public/images/6.png
  ReactWeatherApp/public/images/7.png
  ReactWeatherApp/public/images/8.png
  ReactWeatherApp/public/images/9.png
  ReactWeatherApp/public/images/bgImg.jpg
  ReactWeatherApp/public/index.html
  ReactWeatherApp/public/logo192.png
  ReactWeatherApp/public/logo512.png
  ReactWeatherApp/public/manifest.json
  ReactWeatherApp/public/robots.txt
  ReactWeatherApp/src/App.css
  ReactWeatherApp/src/App.js
  ReactWeatherApp/src/App.test.js
  ReactWeatherApp/src/components/Info1.jsx
  ReactWeatherApp/src/components/Info2.jsx
  ReactWeatherApp/src/components/Info3.jsx
  ReactWeatherApp/src/components/Search.jsx
  ReactWeatherApp/src/index.css
  ReactWeatherApp/src/index.js
  ReactWeatherApp/src/reportWebVitals.js
  ReactWeatherApp/src/setupTests.js
Labels: dino-accepted, open-odyssey

#252 added CSS Animation Studio
  css-animation-studio/LICENSE
  css-animation-studio/README.md
  css-animation-studio/index.html
  css-animation-studio/script.js
  css-animation-studio/style.css
Labels: dino-accepted, open-odyssey

#253 Added Max Dirt Bike game in React JS
  max-dirt-bike/.gitignore
  max-dirt-bike/package-lock.json
  max-dirt-bike/package.json
  max-dirt-bike/public/favicon.ico
  max-dirt-bike/public/game/maxdirtbike.swf
  max-dirt-bike/public/index.html
  max-dirt-bike/public/logo192.png
  max-dirt-bike/public/logo512.png
  max-dirt-bike/public/manifest.json
  max-dirt-bike/public/robots.txt
  max-dirt-bike/src/App.css
  max-dirt-bike/src/App.js
  max-dirt-bike/src/App.test.js
  max-dirt-bike/src/components/GamePlayer.css
  max-dirt-bike/src/components/GamePlayer.js
  max-dirt-bike/src/index.css
  max-dirt-bike/src/index.js
  max-dirt-bike/src/logo.svg
  max-dirt-bike/src/reportWebVitals.js
  max-dirt-bike/src/setupTests.js
Labels: dino-accepted, open-odyssey

#254 Added Mini-Putt game in React JS
  mini-putt/.gitignore
  mini-putt/package-lock.json
  mini-putt/package.json
  mini-putt/public/favicon.ico
  mini-putt/public/game/miniputt.swf
  mini-putt/public/index.html
  mini-putt/public/logo192.png
  mini-putt/public/logo512.png
  mini-putt/public/manifest.json
  mini-putt/public/robots.txt
  mini-putt/src/App.css
  mini-putt/src/App.js
  mini-putt/src/App.test.js
  mini-putt/src/components/GamePlayer.css
  mini-putt/src/components/GamePlayer.js
  mini-putt/src/index.css
  mini-putt/src/index.js
  mini-putt/src/logo.svg
  mini-putt/src/reportWebVitals.js
  mini-putt/src/setupTests.js
Labels: dino-accepted, open-odyssey

#255 Added Helicopter game in React JS
  helicopter-game/.gitignore
  helicopter-game/package-lock.json
  helicopter-game/package.json
  helicopter-game/public/favicon.ico
  helicopter-game/public/game/helicoptergame.swf
  helicopter-game/public/index.html
  helicopter-game/public/logo192.png
  helicopter-game/public/logo512.png
  helicopter-game/public/manifest.json
  helicopter-game/public/robots.txt
  helicopter-game/src/App.css
  helicopter-game/src/App.js
  helicopter-game/src/App.test.js
  helicopter-game/src/components/GamePlayer.css
  helicopter-game/src/components/GamePlayer.js
  helicopter-game/src/index.css
  helicopter-game/src/index.js
  helicopter-game/src/logo.svg
  helicopter-game/src/reportWebVitals.js
  helicopter-game/src/setupTests.js
Labels: dino-accepted, open-odyssey

#256 Added Stunt Dirt Bike game in React JS
  stunt-dirt-bike/.gitignore
  stunt-dirt-bike/package-lock.json
  stunt-dirt-bike/package.json
  stunt-dirt-bike/public/favicon.ico
  stunt-dirt-bike/public/game/stuntdirtbike.swf
  stunt-dirt-bike/public/index.html
  stunt-dirt-bike/public/logo192.png
  stunt-dirt-bike/public/logo512.png
  stunt-dirt-bike/public/manifest.json
  stunt-dirt-bike/public/robots.txt
  stunt-dirt-bike/src/App.css
  stunt-dirt-bike/src/App.js
  stunt-dirt-bike/src/App.test.js
  stunt-dirt-bike/src/components/GamePlayer.css
  stunt-dirt-bike/src/components/GamePlayer.js
  stunt-dirt-bike/src/index.css
  stunt-dirt-bike/src/index.js
  stunt-dirt-bike/src/logo.svg
  stunt-dirt-bike/src/reportWebVitals.js
  stunt-dirt-bike/src/setupTests.js
Labels: dino-accepted, open-odyssey

#257 Added Curveball game in React JS
  curveball-game/.gitignore
  curveball-game/package-lock.json
  curveball-game/package.json
  curveball-game/public/favicon.ico
  curveball-game/public/game/curveball.swf
  curveball-game/public/index.html
  curveball-game/public/logo192.png
  curveball-game/public/logo512.png
  curveball-game/public/manifest.json
  curveball-game/public/robots.txt
  curveball-game/src/App.css
  curveball-game/src/App.js
  curveball-game/src/App.test.js
  curveball-game/src/components/GamePlayer.css
  curveball-game/src/components/GamePlayer.js
  curveball-game/src/index.css
  curveball-game/src/index.js
  curveball-game/src/logo.svg
  curveball-game/src/reportWebVitals.js
  curveball-game/src/setupTests.js
Labels: dino-accepted, open-odyssey

#258 Added Bloons TD 2 game in React JS
  bloons-td-2/.gitignore
  bloons-td-2/package-lock.json
  bloons-td-2/package.json
  bloons-td-2/public/favicon.ico
  bloons-td-2/public/game/bloonstd2.swf
  bloons-td-2/public/index.html
  bloons-td-2/public/logo192.png
  bloons-td-2/public/logo512.png
  bloons-td-2/public/manifest.json
  bloons-td-2/public/robots.txt
  bloons-td-2/src/App.css
  bloons-td-2/src/App.js
  bloons-td-2/src/App.test.js
  bloons-td-2/src/components/GamePlayer.css
  bloons-td-2/src/components/GamePlayer.js
  bloons-td-2/src/index.css
  bloons-td-2/src/index.js
  bloons-td-2/src/logo.svg
  bloons-td-2/src/reportWebVitals.js
  bloons-td-2/src/setupTests.js
Labels: dino-accepted, open-odyssey

#259 Added Bloons TD 3 game in React JS
  bloons-td-3/.gitignore
  bloons-td-3/package-lock.json
  bloons-td-3/package.json
  bloons-td-3/public/favicon.ico
  bloons-td-3/public/game/bloonstd3.swf
  bloons-td-3/public/index.html
  bloons-td-3/public/logo192.png
  bloons-td-3/public/logo512.png
  bloons-td-3/public/manifest.json
  bloons-td-3/public/robots.txt
  bloons-td-3/src/App.css
  bloons-td-3/src/App.js
  bloons-td-3/src/App.test.js
  bloons-td-3/src/components/GamePlayer.css
  bloons-td-3/src/components/GamePlayer.js
  bloons-td-3/src/index.css
  bloons-td-3/src/index.js
  bloons-td-3/src/logo.svg
  bloons-td-3/src/reportWebVitals.js
  bloons-td-3/src/setupTests.js
Labels: dino-accepted, open-odyssey

#262 Added Raiden X game in React JS
  raiden-x/.gitignore
  raiden-x/package-lock.json
  raiden-x/package.json
  raiden-x/public/favicon.ico
  raiden-x/public/game/raiden-x.swf
  raiden-x/public/index.html
  raiden-x/public/logo192.png
  raiden-x/public/logo512.png
  raiden-x/public/manifest.json
  raiden-x/public/robots.txt
  raiden-x/src/App.css
  raiden-x/src/App.js
  raiden-x/src/App.test.js
  raiden-x/src/components/GamePlayer.css
  raiden-x/src/components/GamePlayer.js
  raiden-x/src/index.css
  raiden-x/src/index.js
  raiden-x/src/logo.svg
  raiden-x/src/reportWebVitals.js
  raiden-x/src/setupTests.js
Labels: dino-accepted, open-odyssey

#263 Added Soulmech: Shinobu game in React JS
  soulmech-shinobu/.gitignore
  soulmech-shinobu/package-lock.json
  soulmech-shinobu/package.json
  soulmech-shinobu/public/favicon.ico
  soulmech-shinobu/public/game/shinobu.swf
  soulmech-shinobu/public/index.html
  soulmech-shinobu/public/logo192.png
  soulmech-shinobu/public/logo512.png
  soulmech-shinobu/public/manifest.json
  soulmech-shinobu/public/robots.txt
  soulmech-shinobu/src/App.css
  soulmech-shinobu/src/App.js
  soulmech-shinobu/src/App.test.js
  soulmech-shinobu/src/components/GamePlayer.css
  soulmech-shinobu/src/components/GamePlayer.js
  soulmech-shinobu/src/index.css
  soulmech-shinobu/src/index.js
  soulmech-shinobu/src/logo.svg
  soulmech-shinobu/src/reportWebVitals.js
  soulmech-shinobu/src/setupTests.js
Labels: dino-accepted, open-odyssey

#264 Added Bloody Rage game in React JS
  bloody-rage/.gitignore
  bloody-rage/package-lock.json
  bloody-rage/package.json
  bloody-rage/public/favicon.ico
  bloody-rage/public/game/bloodyrage.swf
  bloody-rage/public/index.html
  bloody-rage/public/logo192.png
  bloody-rage/public/logo512.png
  bloody-rage/public/manifest.json
  bloody-rage/public/robots.txt
  bloody-rage/src/App.css
  bloody-rage/src/App.js
  bloody-rage/src/App.test.js
  bloody-rage/src/components/GamePlayer.css
  bloody-rage/src/components/GamePlayer.js
  bloody-rage/src/index.css
  bloody-rage/src/index.js
  bloody-rage/src/logo.svg
  bloody-rage/src/reportWebVitals.js
  bloody-rage/src/setupTests.js
Labels: dino-accepted, open-odyssey

#265 Added World Domination game in React JS
  world-domination/.gitignore
  world-domination/package-lock.json
  world-domination/package.json
  world-domination/public/favicon.ico
  world-domination/public/game/world-domination.swf
  world-domination/public/index.html
  world-domination/public/logo192.png
  world-domination/public/logo512.png
  world-domination/public/manifest.json
  world-domination/public/robots.txt
  world-domination/src/App.css
  world-domination/src/App.js
  world-domination/src/App.test.js
  world-domination/src/components/GamePlayer.css
  world-domination/src/components/GamePlayer.js
  world-domination/src/index.css
  world-domination/src/index.js
  world-domination/src/logo.svg
  world-domination/src/reportWebVitals.js
  world-domination/src/setupTests.js
Labels: dino-accepted, open-odyssey

#266 added HTML Structure Puzzler
  html-structure-puzzler/LICENSE
  html-structure-puzzler/README.md
  html-structure-puzzler/index.html
  html-structure-puzzler/script.js
  html-structure-puzzler/style.css
Labels: dino-accepted, open-odyssey

#267 added CSS Grid Master
  css-grid-master/LICENSE
  css-grid-master/README.md
  css-grid-master/index.html
  css-grid-master/script.js
  css-grid-master/style.css
Labels: dino-accepted, open-odyssey

#268 added JavaScript DOM Manipulation Challenge
  dom-manipulation-challenge/LICENSE
  dom-manipulation-challenge/README.md
  dom-manipulation-challenge/index.html
  dom-manipulation-challenge/script.js
  dom-manipulation-challenge/style.css
Labels: dino-accepted, open-odyssey

#269 added Responsive Web Design Simulator
  responsive-web-design-simulator/LICENSE
  responsive-web-design-simulator/README.md
  responsive-web-design-simulator/index.html
  responsive-web-design-simulator/script.js
  responsive-web-design-simulator/style.css
Labels: dino-accepted, open-odyssey

#270 Added Stunt Bike Draw game in React JS
  stunt-bike-draw/.gitignore
  stunt-bike-draw/package-lock.json
  stunt-bike-draw/package.json
  stunt-bike-draw/public/favicon.ico
  stunt-bike-draw/public/game/stuntbike.swf
  stunt-bike-draw/public/index.html
  stunt-bike-draw/public/logo192.png
  stunt-bike-draw/public/logo512.png
  stunt-bike-draw/public/manifest.json
  stunt-bike-draw/public/robots.txt
  stunt-bike-draw/src/App.css
  stunt-bike-draw/src/App.js
  stunt-bike-draw/src/App.test.js
  stunt-bike-draw/src/components/GamePlayer.css
  stunt-bike-draw/src/components/GamePlayer.js
  stunt-bike-draw/src/index.css
  stunt-bike-draw/src/index.js
  stunt-bike-draw/src/logo.svg
  stunt-bike-draw/src/reportWebVitals.js
  stunt-bike-draw/src/setupTests.js
Labels: dino-accepted, open-odyssey

#271 added CSS Selector Showdown
  css-selector-showdown/LICENSE
  css-selector-showdown/README.md
  css-selector-showdown/index.html
  css-selector-showdown/script.js
  css-selector-showdown/style.css
Labels: dino-accepted, open-odyssey

#272 added JavaScript Algorithm Arena
  js-algorithm-arena/LICENSE
  js-algorithm-arena/README.md
  js-algorithm-arena/index.html
  js-algorithm-arena/script.js
  js-algorithm-arena/style.css
Labels: dino-accepted, open-odyssey

#273 Added Disorderly game in React JS
  disorderly-game/.gitignore
  disorderly-game/package-lock.json
  disorderly-game/package.json
  disorderly-game/public/favicon.ico
  disorderly-game/public/game/disorderly.swf
  disorderly-game/public/index.html
  disorderly-game/public/logo192.png
  disorderly-game/public/logo512.png
  disorderly-game/public/manifest.json
  disorderly-game/public/robots.txt
  disorderly-game/src/App.css
  disorderly-game/src/App.js
  disorderly-game/src/App.test.js
  disorderly-game/src/components/GamePlayer.css
  disorderly-game/src/components/GamePlayer.js
  disorderly-game/src/index.css
  disorderly-game/src/index.js
  disorderly-game/src/logo.svg
  disorderly-game/src/reportWebVitals.js
  disorderly-game/src/setupTests.js
Labels: dino-accepted, open-odyssey

#275 added CSS Flexbox Ninja
  css-flexbox-ninja/LICENSE
  css-flexbox-ninja/README.md
  css-flexbox-ninja/index.html
  css-flexbox-ninja/script.js
  css-flexbox-ninja/style.css
Labels: dino-accepted, open-odyssey

#278 added SVG Animation Challenge
  svg-animation-challenge/LICENSE
  svg-animation-challenge/README.md
  svg-animation-challenge/index.html
  svg-animation-challenge/script.js
  svg-animation-challenge/style.css
Labels: dino-accepted, open-odyssey

#279 Added 3 Foot Ninja game in React JS
  three-foot-ninja/.gitignore
  three-foot-ninja/package-lock.json
  three-foot-ninja/package.json
  three-foot-ninja/public/favicon.ico
  three-foot-ninja/public/game/three-foot-ninja.swf
  three-foot-ninja/public/index.html
  three-foot-ninja/public/logo192.png
  three-foot-ninja/public/logo512.png
  three-foot-ninja/public/manifest.json
  three-foot-ninja/public/robots.txt
  three-foot-ninja/src/App.css
  three-foot-ninja/src/App.js
  three-foot-ninja/src/App.test.js
  three-foot-ninja/src/components/GamePlayer.css
  three-foot-ninja/src/components/GamePlayer.js
  three-foot-ninja/src/index.css
  three-foot-ninja/src/index.js
  three-foot-ninja/src/logo.svg
  three-foot-ninja/src/reportWebVitals.js
  three-foot-ninja/src/setupTests.js
Labels: dino-accepted, open-odyssey

#280 added JavaScript Scope and Closure Adventure
  js-scope-closure-adventure/LICENSE
  js-scope-closure-adventure/README.md
  js-scope-closure-adventure/index.html
  js-scope-closure-adventure/script.js
  js-scope-closure-adventure/style.css
Labels: dino-accepted, open-odyssey

#225 Added Superfighters game in React JS
  superfighters/.gitignore
  superfighters/package-lock.json
  superfighters/package.json
  superfighters/public/favicon.ico
  superfighters/public/game/superfighters.swf
  superfighters/public/index.html
  superfighters/public/logo192.png
  superfighters/public/logo512.png
  superfighters/public/manifest.json
  superfighters/public/robots.txt
  superfighters/src/App.css
  superfighters/src/App.js
  superfighters/src/App.test.js
  superfighters/src/components/GamePlayer.css
  superfighters/src/components/GamePlayer.js
  superfighters/src/index.css
  superfighters/src/index.js
  superfighters/src/logo.svg
  superfighters/src/reportWebVitals.js
  superfighters/src/setupTests.js
Labels: dino-accepted, open-odyssey

#226 Added Ultimate Sonic game in React JS
  ultimate-sonic/.gitignore
  ultimate-sonic/package-lock.json
  ultimate-sonic/package.json
  ultimate-sonic/public/favicon.ico
  ultimate-sonic/public/game/ultimatesonic.swf
  ultimate-sonic/public/index.html
  ultimate-sonic/public/logo192.png
  ultimate-sonic/public/logo512.png
  ultimate-sonic/public/manifest.json
  ultimate-sonic/public/robots.txt
  ultimate-sonic/src/App.css
  ultimate-sonic/src/App.js
  ultimate-sonic/src/App.test.js
  ultimate-sonic/src/components/GamePlayer.css
  ultimate-sonic/src/components/GamePlayer.js
  ultimate-sonic/src/index.css
  ultimate-sonic/src/index.js
  ultimate-sonic/src/logo.svg
  ultimate-sonic/src/reportWebVitals.js
  ultimate-sonic/src/setupTests.js
Labels: dino-accepted, open-odyssey

#229 Added Breaking the Bank game in React JS
  breaking-the-bank/.gitignore
  breaking-the-bank/package-lock.json
  breaking-the-bank/package.json
  breaking-the-bank/public/favicon.ico
  breaking-the-bank/public/game/breakingthebank.swf
  breaking-the-bank/public/index.html
  breaking-the-bank/public/logo192.png
  breaking-the-bank/public/logo512.png
  breaking-the-bank/public/manifest.json
  breaking-the-bank/public/robots.txt
  breaking-the-bank/src/App.css
  breaking-the-bank/src/App.js
  breaking-the-bank/src/App.test.js
  breaking-the-bank/src/components/GamePlayer.css
  breaking-the-bank/src/components/GamePlayer.js
  breaking-the-bank/src/index.css
  breaking-the-bank/src/index.js
  breaking-the-bank/src/logo.svg
  breaking-the-bank/src/reportWebVitals.js
  breaking-the-bank/src/setupTests.js
Labels: dino-accepted, open-odyssey

#233 added Multi-Step Form Application
  multi-step-form-application/.gitignore
  multi-step-form-application/README.md
  multi-step-form-application/package-lock.json
  multi-step-form-application/package.json
  multi-step-form-application/public/favicon.ico
  multi-step-form-application/public/index.html
  multi-step-form-application/public/logo192.png
  multi-step-form-application/public/logo512.png
  multi-step-form-application/public/manifest.json
  multi-step-form-application/public/robots.txt
  multi-step-form-application/src/App.css
  multi-step-form-application/src/App.js
  multi-step-form-application/src/App.test.js
  multi-step-form-application/src/Questions.js
  multi-step-form-application/src/components/FormItem.js
  multi-step-form-application/src/components/MultiStepForm.js
  multi-step-form-application/src/components/MultiStepProgressBar.css
  multi-step-form-application/src/components/MultiStepProgressBar.js
  multi-step-form-application/src/index.css
  multi-step-form-application/src/index.js
  multi-step-form-application/src/logo.svg
  multi-step-form-application/src/reportWebVitals.js
  multi-step-form-application/src/setupTests.js
Labels: dino-accepted, open-odyssey

#234 new music streaming website
  Laptop UI/index.html
  Laptop UI/style.css
Labels: dino-accepted, open-odyssey

#235 added React Login/Register App
  react-login-register/.gitignore
  react-login-register/README.md
  react-login-register/package-lock.json
  react-login-register/package.json
  react-login-register/public/favicon.ico
  react-login-register/public/index.html
  react-login-register/public/logo192.png
  react-login-register/public/logo512.png
  react-login-register/public/manifest.json
  react-login-register/public/robots.txt
  react-login-register/src/App.css
  react-login-register/src/App.js
  react-login-register/src/App.test.js
  react-login-register/src/Login.jsx
  react-login-register/src/Register.jsx
  react-login-register/src/index.css
  react-login-register/src/index.js
  react-login-register/src/logo.svg
  react-login-register/src/reportWebVitals.js
  react-login-register/src/setupTests.js
Labels: dino-accepted, open-odyssey

#236 Added Johnny Rocketfingers game in React JS
  johnny-rocketfingers/.gitignore
  johnny-rocketfingers/package-lock.json
  johnny-rocketfingers/package.json
  johnny-rocketfingers/public/favicon.ico
  johnny-rocketfingers/public/game/johnny.swf
  johnny-rocketfingers/public/index.html
  johnny-rocketfingers/public/logo192.png
  johnny-rocketfingers/public/logo512.png
  johnny-rocketfingers/public/manifest.json
  johnny-rocketfingers/public/robots.txt
  johnny-rocketfingers/src/App.css
  johnny-rocketfingers/src/App.js
  johnny-rocketfingers/src/App.test.js
  johnny-rocketfingers/src/components/GamePlayer.css
  johnny-rocketfingers/src/components/GamePlayer.js
  johnny-rocketfingers/src/index.css
  johnny-rocketfingers/src/index.js
  johnny-rocketfingers/src/logo.svg
  johnny-rocketfingers/src/reportWebVitals.js
  johnny-rocketfingers/src/setupTests.js
Labels: dino-accepted, open-odyssey

#237 Added Bowman 2 game in React JS
  bowman-two/.gitignore
  bowman-two/package-lock.json
  bowman-two/package.json
  bowman-two/public/favicon.ico
  bowman-two/public/game/bowman2.swf
  bowman-two/public/index.html
  bowman-two/public/logo192.png
  bowman-two/public/logo512.png
  bowman-two/public/manifest.json
  bowman-two/public/robots.txt
  bowman-two/src/App.css
  bowman-two/src/App.js
  bowman-two/src/App.test.js
  bowman-two/src/components/GamePlayer.css
  bowman-two/src/components/GamePlayer.js
  bowman-two/src/index.css
  bowman-two/src/index.js
  bowman-two/src/logo.svg
  bowman-two/src/reportWebVitals.js
  bowman-two/src/setupTests.js
Labels: dino-accepted, open-odyssey

#238 Added my notes recording project
  Notes recorder/index.html
  Notes recorder/index.js
  Notes recorder/style.css
Labels: dino-accepted, open-odyssey

#239 added Time-Traveling Code Editor
  time-traveling-code-editor/LICENSE
  time-traveling-code-editor/README.md
  time-traveling-code-editor/index.html
  time-traveling-code-editor/script.js
  time-traveling-code-editor/style.css
Labels: dino-accepted, open-odyssey

#240 added Web Design Battle Royale
  web-design-battle-royale/LICENSE
  web-design-battle-royale/README.md
  web-design-battle-royale/index.html
  web-design-battle-royale/script.js
  web-design-battle-royale/style.css
Labels: dino-accepted, open-odyssey

#241 added Bug Apocalypse
  bug-apocalypse/LICENSE
  bug-apocalypse/README.md
  bug-apocalypse/index.html
  bug-apocalypse/script.js
  bug-apocalypse/style.css
Labels: dino-accepted, open-odyssey

#243 added CSS Battle: Themed Design Challenge
  css-battle/LICENSE
  css-battle/README.md
  css-battle/index.html
  css-battle/script.js
  css-battle/style.css
Labels: dino-accepted, open-odyssey

#244 added Regex Quest
  regex-quest/LICENSE
  regex-quest/README.md
  regex-quest/index.html
  regex-quest/script.js
  regex-quest/style.css
Labels: dino-accepted, open-odyssey
